'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Roberts Space Industries\StarCitizen\LIVE")>  _
        Public Property SC_Installationpath_LIVE() As String
            Get
                Return CType(Me("SC_Installationpath_LIVE"),String)
            End Get
            Set
                Me("SC_Installationpath_LIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Roberts Space Industries\StarCitizen\PTU")>  _
        Public Property SC_Installationpath_PTU() As String
            Get
                Return CType(Me("SC_Installationpath_PTU"),String)
            End Get
            Set
                Me("SC_Installationpath_PTU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Roberts Space Industries\StarCitizen\EPTU")>  _
        Public Property SC_Installationpath_EPTU() As String
            Get
                Return CType(Me("SC_Installationpath_EPTU"),String)
            End Get
            Set
                Me("SC_Installationpath_EPTU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Roberts Space Industries\StarCitizen\TECH-PREVIEW")>  _
        Public Property SC_Installationpath_TECH_PREVIEW() As String
            Get
                Return CType(Me("SC_Installationpath_TECH_PREVIEW"),String)
            End Get
            Set
                Me("SC_Installationpath_TECH_PREVIEW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Roberts Space Industries\RSI Launcher")>  _
        Public Property LC_Installationpath() As String
            Get
                Return CType(Me("LC_Installationpath"),String)
            End Get
            Set
                Me("LC_Installationpath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eng")>  _
        Public Property lang_LIVE() As String
            Get
                Return CType(Me("lang_LIVE"),String)
            End Get
            Set
                Me("lang_LIVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eng")>  _
        Public Property lang_PTU() As String
            Get
                Return CType(Me("lang_PTU"),String)
            End Get
            Set
                Me("lang_PTU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eng")>  _
        Public Property lang_EPTU() As String
            Get
                Return CType(Me("lang_EPTU"),String)
            End Get
            Set
                Me("lang_EPTU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eng")>  _
        Public Property lang_TECH_PREVIEW() As String
            Get
                Return CType(Me("lang_TECH_PREVIEW"),String)
            End Get
            Set
                Me("lang_TECH_PREVIEW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property de_full_flag() As Boolean
            Get
                Return CType(Me("de_full_flag"),Boolean)
            End Get
            Set
                Me("de_full_flag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Roberts Space Industries\StarCitizen\HOTFIX")>  _
        Public Property SC_Installationpath_HOTFIX() As String
            Get
                Return CType(Me("SC_Installationpath_HOTFIX"),String)
            End Get
            Set
                Me("SC_Installationpath_HOTFIX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eng")>  _
        Public Property lang_HOTFIX() As String
            Get
                Return CType(Me("lang_HOTFIX"),String)
            End Get
            Set
                Me("lang_HOTFIX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LIVE")>  _
        Public Property HOTFIX_ini() As String
            Get
                Return CType(Me("HOTFIX_ini"),String)
            End Get
            Set
                Me("HOTFIX_ini") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LIVE")>  _
        Public Property TECH_PREVIEW_ini() As String
            Get
                Return CType(Me("TECH_PREVIEW_ini"),String)
            End Get
            Set
                Me("TECH_PREVIEW_ini") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Verbose() As Boolean
            Get
                Return CType(Me("Verbose"),Boolean)
            End Get
            Set
                Me("Verbose") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.scdl.My.MySettings
            Get
                Return Global.scdl.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
